### ISSUE TITLE
Student task list not clear for submitted tasks

### ISSUE THREAD

**Issue by tgaffey** [SlateFoundation/slate-cbl#540] opened 2020-11-05 18:54 UTC
If a task is submitted, the color or hashing doesnt change. The task also changes color to red after the due date passes even if they submitted on time. This makes it difficult for students to immediately understand their task list. I am not so sure its as simple as hashing things out or messing with the colors.

From trello: https://trello.com/c/lLBODFiI

**Comment by katjost** [comment] 2021-02-16 19:21
This is a duplicate of #547

**Closed as completed by katjost** 2021-02-16 19:21 UTC
